config/routes.rb
Rails.application.routes.draw do
  resources :books
  root to: 'home#top'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
#どの投稿データを表示するか判別するための記述
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def top
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @books=Book.new
  end

  def create
    #データを受け取り新規登録するためのインスタンスインスタンス作成
    @book = Book.new(book_params)
    #データをデータベースへ保存する
    if @book.save
    #book一覧画面へリダイレクト
    flash[:notice] = "successfully create."
    redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end

  def index
   @book = Book.new
   @books = Book.all
  end

  def show
   @book = Book.find(params[:id])
  end

  def edit
   @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "successfully updated."
     redirect_to book_path(@book.id)
    else
     render :edit
    end
  end

  def destroy
   book= Book.find(params[:id])
   book.destroy
   flash[:notice] = "successfully destroy."
   redirect_to '/books'
  end

 private
 #ストロングパラメーター
  def book_params
     params.require(:book).permit(:title,:body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error
  <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
 <% end %>
<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

<h4>title</h4>
<%= f.text_field :title %>

<div>
 <%= flash[:notice] %>
</div>

<h4>body</h4>
<%= f.text_area :body %>

<%= f.submit 'Update Book' %>
<% end %>
<%= link_to "Show", book_path(@book.id) %> |
<%= link_to "Back",books_path %>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div>

<h1>Books</h1>
<table>
 <tbody>
    <!--テーブル上部の記述-->
    <thead>
      <tr>
      <th>title</th>
      <th>body</th>
      <th colspan ="3"></th>
      </tr>
    </thead>
<!--投稿一覧を表示する-->
<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to "Show", book_path(book.id) %></td>
    <td><%= link_to "Edit", edit_book_path(book.id) %></td>
    <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？"  %></td>
  </tr>
<% end %>
 </tbody>
</table>
<!--投稿機能-->
<h2>New book</h2>
 <% if @book.errors.any? %>
  <%= @book.errors.count %>error
  <ul>
   <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
   <% end %>
  </ul>
 <% end %>

<%= form_with model: @book do |f| %>
  <h4>title</h4>
  <%= f.text_field :title %>

  <h4>body</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book'%>
<% end %>

app/views/books/show.html.erb
<div>
<%= flash[:notice] %>
</div>

<h2>title</h2>
<p><%= @book.title %></p>
<h2>body</h2>
<p><%= @book.body %></p>
<%= link_to "Edit", edit_book_path(@book.id) %>
<%= link_to "Back" , books_path %>

app/views/home/top.html.erb
<h1>Bookers</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や</p><p>印象を共有し交換することが出来ます</p>


<p><a href="/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>